// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyMQQCw6rARHLv9KY4LZlHIifzPunN5UY',
    appId: '1:129258897545:web:8951b7958fd5e75c998658',
    messagingSenderId: '129258897545',
    projectId: 'medzo-18785',
    authDomain: 'medzo-18785.firebaseapp.com',
    storageBucket: 'medzo-18785.appspot.com',
    measurementId: 'G-L8ZG8G3EL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8n6lo9xWbroYTo0T6AoS4aggcNQyYUBg',
    appId: '1:129258897545:android:b704a5ad45853d16998658',
    messagingSenderId: '129258897545',
    projectId: 'medzo-18785',
    storageBucket: 'medzo-18785.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuB5VhIVwvDN_u_8Fi3Te5N8QSG37Jje0',
    appId: '1:129258897545:ios:66f2028dc373a609998658',
    messagingSenderId: '129258897545',
    projectId: 'medzo-18785',
    storageBucket: 'medzo-18785.appspot.com',
    androidClientId: '129258897545-2pptudmm7og9mc4riakalcc53psg5b03.apps.googleusercontent.com',
    iosClientId: '129258897545-41t8gqfb0lglsbtbtigqjnbbrvjp2rqe.apps.googleusercontent.com',
    iosBundleId: 'com.corange.medzo',
  );
}
