class AppImages {
  static const String logo = 'assets/images/Logo.png';
  static const String logo1 = 'assets/images/Logo.svg';
  static const String medzo = 'assets/images/medzo.svg';
  static const String google = 'assets/images/google.svg';
  static const String apple = 'assets/images/apple.svg';
  static const String medzologo = 'assets/images/medzo logo.svg';
  static const String alergies = 'assets/images/alergies.svg';
  static const String antibiotic = 'assets/images/anti_biotic.svg';
  static const String antidepreset = 'assets/images/anti_depresent.svg';
  static const String cardiovascular = 'assets/images/cardiovascular.svg';
  static const String chat_message = 'assets/images/chat_message.svg';
  static const String devices = 'assets/images/devices.svg';
  static const String profile_picture = 'assets/appicon.png';
  static const String hypnotics = 'assets/images/hypnotics.svg';
  static const String mobile_image = 'assets/images/mobile_image.svg';
  static const String painkiller = 'assets/images/painkiller.svg';
  static const String pill = 'assets/images/pill.png';
  static const String pillw = 'assets/images/pillwhite.png';
  static const String supplements = 'assets/images/supplements.svg';
  static const String splashback = 'assets/images/splash_background.png';
  static const String chatback = 'assets/images/chat_back.png';
  static const String medicineBox1 = 'assets/images/medicine_box.png';
  static const String medzoLineLogo = 'assets/images/medzo_linelogo.svg';
  static const String newMedzoLineLogo = 'assets/images/newmedzoline.svg';
  static const String medzoLineLogo1 = 'assets/images/medzo_linelogo.png';
  static const String homeImage = 'assets/images/homeImage.jpg';

  // TODO: add asses
  static const String errorImage = 'assets/error_image.png';
  static const String cameraIcon =
      'assets/signin_signup_screen/camera_icon.png';
  static const String unselectedPic = 'assets/photounselect.png';
  static const String crossIcon = 'assets/cross_icon.png';
  static const String group = 'assets/group.png';
  static const String gallaryIcon = 'assets/gallary_icon.png';
  static const String addEventsIcon = 'assets/add events.png';
}

class SvgIcon {
  static const String newMedzo = 'assets/icons/newmedzo.svg';
  static const String alcohol = 'assets/icons/alcohol_icon.svg';
  static const String arrowup = 'assets/icons/arrowup.svg';
  static const String add = 'assets/icons/add.svg';
  static const String arrowright = 'assets/icons/arrowright.svg';
  static const String arrowdown = 'assets/icons/arrowdown.svg';
  static const String antibiotic = 'assets/icons/antibiotic_icon.svg';
  static const String at_icon = 'assets/icons/at_icon.svg';
  static const String baby = 'assets/icons/baby_icon.svg';
  static const String backarrow = 'assets/icons/back_arrow.svg';
  static const String bookmark = 'assets/icons/bookmark_icon.svg';
  static const String fillbookmark = 'assets/icons/fill_bookmark.svg';
  static const String chat = 'assets/icons/chat_icon.svg';
  static const String chat2 = 'assets/icons/chat2.svg';
  static const String chathome = 'assets/icons/chathome.svg';
  static const String skip = 'assets/icons/skip.svg';
  static const String camera = 'assets/icons/camera.svg';
  static const String likePost = 'assets/icons/likePost.svg';
  static const String commentPost = 'assets/icons/commentPost.svg';
  static const String camerapng = 'assets/icons/camera.png';
  static const String gallery = 'assets/icons/gallery.svg';
  static const String gallerypng = 'assets/icons/gallery.png';
  static const String check_circle = 'assets/icons/check_circle_icon.svg';
  static const String failure =
      'assets/icons/check_circle_icon.svg'; // TODO: change image
  static const String delete = 'assets/icons/delete_icon.svg';
  static const String email = 'assets/icons/email_icon.svg';
  static const String info = 'assets/icons/Info.svg';
  static const String experts = 'assets/icons/experts.svg';
  static const String expert = 'assets/icons/expert.png';
  static const String fill_radio = 'assets/icons/fill_radio_icon.svg';
  static const String first_aid = 'assets/icons/first_aid_icon.svg';
  static const String fillcheck = 'assets/icons/fillcheck.svg';
  static const String heartbeat = 'assets/icons/heartbeat_icon.svg';
  static const String home_medzo = 'assets/icons/home_medzo_icon.svg';
  static const String key = 'assets/icons/key_icon.svg';
  static const String more = 'assets/icons/more.svg';
  static const String pass_eye = 'assets/icons/pass_eye.svg';
  static const String password = 'assets/icons/password_icon.svg';
  static const String pen = 'assets/icons/pen_icon.svg';
  static const String pencil = 'assets/icons/pencil_icon.svg';
  static const String pencil_simple = 'assets/icons/pencil_simple_icon.svg';
  static const String person_run = 'assets/icons/person_run_icon.svg';
  static const String pill = 'assets/icons/pill_icon.svg';
  static const String post = 'assets/icons/post_icon.svg';
  static const String profile = 'assets/icons/profile_icon.svg';
  static const String qrcode = 'assets/icons/qrcode_icon.svg';
  static const String Rx = 'assets/icons/Rx_icon.svg';
  static const String save = 'assets/icons/save_icon.svg';
  static const String send = 'assets/icons/send_icon.svg';
  static const String signout = 'assets/icons/signout_icon.svg';
  static const String logoutdialogue = 'assets/icons/logout_dialogue.svg';
  static const String search = 'assets/icons/search.svg';
  static const String smiley = 'assets/icons/smiley_icon.svg';
  static const String snowflack = 'assets/icons/snowflack_icon.svg';
  static const String upload_image = 'assets/icons/upload_image_icon.svg';
  static const String verify = 'assets/icons/verify_icon.svg';
  static const String virus = 'assets/icons/virus_icon.svg';
  static const String nodata = 'assets/icons/nodata1.png';
  static const String masksad = 'assets/icons/masksad_icon.svg';
}
